name: aplikasi_bem
description: "Aplikasi Buku Ende Methodist Offline"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

  # Database lokal
  sqflite: ^2.3.0
  path: ^1.8.3

  # Audio Player (Untuk MP3/MP4/M4A)
  audioplayers: ^5.2.1

  # PDF Viewer (Untuk NRM) -- WAJIB ADA --
  syncfusion_flutter_pdfviewer: ^32.1.22

  # Animasi UI
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo_methodist.png
    - assets/BEM/BEM_teks/
    - assets/BEM/BEM_audio/
    - assets/NRM/NRM_teks/
    - assets/NRM/NRM_audio/